### ISSUE TITLE
Was this based on any book?

### ISSUE THREAD

**Issue by lancejpollard** [olivierverdier/GeometricAlgebra#3]
Wondering if I could follow along by purchasing a book, perhaps, that might have been used as a natural-language base upon which to create the Coq formalization. Is there a book used her to construct this formalization?

Looking forward to your response! Thank you.

**Comment by olivierverdier** [comment]
You should ask this question to the [original authors of the project](http://www-sop.inria.fr/marelle/GeometricAlgebra/).
